### ISSUE TITLE
Add way to exit `/console`

### ISSUE THREAD

**Issue by henrybarreto** [henrybarreto/mytv#2]
When you access the `/console`, you cannot exit that page without using the browser interface or some browser's shortcut.

I believe that some button to back to home could be helpful.

**Comment by prateek565** [comment]
Hey there I would like to work  on it assign it to me .

**Comment by henrybarreto** [comment]
> Hey there I would like to work on it assign it to me .

Nice to know! If you need any help; feel free to ask; right?

**Comment by henrybarreto** [comment]
It is worth to say you need to run, beyond the `npm run dev`, the `npm run backend`, to `/console` work.
