### ISSUE TITLE
Redirect from splash screen to home after a while

### ISSUE THREAD

**Issue by henrybarreto** [henrybarreto/mytv#3]
It is simple; just redirect to `/home` route after a while or after a callback function return a data. It will be useful when the data loading on that screen be implemented.

**Comment by Erum640** [comment]
Please assign me this issue . I want to work on it.

**Comment by Im-Kunal-13** [comment]
@henrybarreto I would like to work on this issue. Can you assign this to me?

**Comment by henrybarreto** [comment]
The project will not use the splash anymore
